
name: Release NPM Package

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: "Release type (minor, major, patch):"
        required: true
        default: patch
  release:
    types:
      - created

jobs:
  build_ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
      - name: Build
        run: cd distill && cargo build --release
      - name: Rename Binary
        run: mv distill/target/release/distill distill-for-ubuntu
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: distill-for-ubuntu
          path: dist/

  build_macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
      - name: Build
        run: cd distill && cargo build --release
      - name: Rename Binary
        run: mv distill/target/release/distill distill-for-osx
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: distill-for-osx
          path: dist/

  build_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain
        uses: actions-rs/toolchain@v1
      - name: Build
        run: cd distill && cargo build --release
      - name: Rename Binary
        run: mv distill/target/release/distill.exe distill-for-windows.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: distill-for-windows.exe
          path: dist/

  publish_npm_package:
    needs: [build_ubuntu, build_macos, build_windows]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: actions/download-artifact@v2
        with:
          path: temp_dist 
      - name: Flatten Binary Directory
        run: |
          mkdir dist
          mv temp_dist/**/* dist || true
          rmdir dist/**/* || true
          rm -rf temp_dist
      - name: Grant Permissions
        run: chmod +x dist/*
      - name: Setup Package Registry Credentials
        run: echo "not necessary yet!"
      - name: Preview Publish
        run: npm pack
      - name: Publish Package
        run: echo "not necessary yet!"
        
  release-candidate:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      NEW_TAG: ${{ steps.version.outputs.NEW_TAG }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
#           ref: ${{ env.GIT_REF }}
#           token: ${{ secrets.ACTION_TOKEN }}

      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@master
        id: version_bump
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        with:
          target-branch: ${{ env.GIT_REF }}
          default: ${{ github.event.inputs.release_type }}
          minor-wording: 'feature,MAGWEB'
          major-wording: 'BREAKING'
          patch-wording: 'hotfix,HOTFIX'
          commit-message: 'CI: version bump to {{version}} [skip ci]'
          tag-prefix: 'v'

      - name: Create Changelog
        id: changelog
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
        uses: gandarez/changelog-action@v1.0.4
        with:
          exclude: |
            ^CI: version bump to.*

      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version_bump.outputs.newTag }}
          release_name: ${{ steps.version_bump.outputs.newTag }}
          body: ${{steps.changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
